# Copyright 2023 Amazon.com, Inc. or its affiliates. 
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 https://aws.amazon.com/apache-2-0/

name: Sonatype SCA Scanning
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SonatypeUrl: "https://finos.sonatype.app/platform/"
  SonatypeAppId: "htc-grid"
  SonatypeScanTarget: "."
  ExcludeDirectory: "**/docs/ **/examples/ **/.*'"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Create "dist" (Workaround)
        run : |
          removeDeps=("privateapi-1.0.0-py3-none-any.whl" "publicapi-1.0.0-py3-none-any.whl" "api-0.1-py3-none-any.whl" "utils-0.1-py3-none-any.whl")
          mkdir dist/
          mkdir dist/python/
          cd dist/python/
          for i in ${list[@]}; do
            echo "Temporary File" > $i
          done
          ls
      
      - name: Download Python Libraries
        run : |
          removeDeps=("privateapi-1.0.0-py3-none-any.whl" "publicapi-1.0.0-py3-none-any.whl" "api-0.1-py3-none-any.whl" "utils-0.1-py3-none-any.whl")
          projRoot=`pwd`
          list=$(find "." -name 'requirements.txt')
          
          for i in $list; do
              echo ""
              echo "Requirements at: $i"
              j="${i/'requirements.txt'/}" # Remove 'requirements.txt'
              cd $j
              
              # Remove dist dependencies
              for rem in ${removeDeps[@]}; do
                  sed -i "s,./../../../../dist/python/$rem,,g" requirements.txt
                  # sed -i '' "s/$rem/ooo/g" requirements.txt
              done
              cat requirements.txt
              mkdir pip-modules
              pip install -r requirements.txt
              pip freeze > pip-modules/requirements.txt
              pip download -r requirements.txt -d pip-modules
              cd $projRoot
          done
          

      ###########################
      ## Sonatype SCA Scanning ##
      ###########################
      - name: Sonatype Lifecycle SCA Scan
        id: evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: ${{ env.SonatypeUrl }}
          username: ${{ secrets.SONATYPE_SCANNER_USERNAME }}
          password: ${{ secrets.SONATYPE_SCANNER_PASSWORD }}
          application-id: ${{ env.SonatypeAppId }}
          stage: "build"
          scan-targets: ${{ env.SonatypeScanTarget }}
          module-exclude: ${{ env.ExcludeDirectory }}

      - name: Save Sonatype SBOM
        uses: sonatype/actions/fetch-sbom@v1
        if: always() && steps.evaluate.outputs.scan-id
        with:
          iq-server-url: ${{ env.SonatypeUrl }}
          username: ${{ secrets.SONATYPE_SCANNER_USERNAME }}
          password: ${{ secrets.SONATYPE_SCANNER_PASSWORD }}
          application-id: ${{ env.SonatypeAppId }}
          scan-id: ${{ steps.evaluate.outputs.scan-id }}
          sbom-standard: spdx
          sbom-version: 2.3
          artifact-name: ${{ env.SonatypeAppId }}-bom
